[package]
name = "bcast"
version = "0.1.0"
edition = "2021"
rust-version = "1.73.0"

[dependencies]
thiserror = "2.0.3"
crossbeam-utils = "0.8.20"

[dev-dependencies]
anyhow = "1.0.93"
rand = "0.8.5"
memmap2 = "0.9.5"